### ISSUE TITLE
Incorrect conversion of dashes to en-dashes

### ISSUE THREAD

**Issue by guyru** [cpuguy83/go-md2man#101]
Hi,

Blackfriday used for the markdown conversion converts dashes to en-dashes. While this might look pretty, for man pages it makes little sense, as command line arguments use regular dashes. It makes search the resulting manpage for CLI flags harder, as well as preventing copying of CLI flags directly from the manpage to the shell.

I believe this feature should be disabled.

See for example https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051409

Thanks,
Guy

**Comment by debarshiray** [comment]
Are you really sure that those characters are En Dash (ie., – or 0x2013) and not Hyphen (ie., ‐ or 0x2010) ?

I think that this issue is triggered by GNU roff 1.23 no longer remapping unescaped Hyphen-Minus (ie., - or 0x2D) characters in the input to Hyphen-Minus in the output.  Instead, it follows the specified behaviour of converting unescaped Hyphen-Minus characters in the input to Hyphen (ie., ‐ or 0x2010) in the output.  To get Hyphen-Minus characters in the output, one needs to escape the Hyphen-Minus with a backslash (ie., \-) in the input.

See:
https://lwn.net/Articles/947941/
https://lists.gnu.org/archive/html/info-gnu/2023-07/msg00001.html
https://git.savannah.gnu.org/cgit/groff.git/tree/PROBLEMS?h=1.23.0#n82

Unfortunately, escaping the Hyphen-Minus characters in Markdown doesn't have the intended effect of having Hyphen-Minus in the generated manual pages.  It looks like something in the Markdown to troff conversion eats up the backslash characters used for escaping and we get a Hyphen in the output anyway.  Unless I am missing something.

I am no expert in Markdown or troff, but given some pointers I am willing to make some effort to improve the correctness of the manuals.

/cc @paravoid @g-branden-robinson

**Comment by guyru** [comment]
I'm not sure what changed the issue, but I no longer experience the issue on up-to-date Debian Unstable.
